# Generated by Django 4.1 on 2022-08-18 18:59

from pydoc import describe
from django.db import migrations


def create_data(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product(name="Banaanidega Sokk", description = "Sokk millel on hästi nunnud banaanid. jAAA üli pehme!", price="2.3").save() 

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
